(RUSSNG-114) /etc/init.d/russ should only report on runnable servers
If there is no configuration for a server, then it should
not show up as starting/stopping. This change updates
/etc/init.d/russ to be smarter and the /etc/russ/init
scripts to use a check operation.

diff --git a/library/static/etc/init.d/russ b/library/static/etc/init.d/russ
--- a/library/static/etc/init.d/russ
+++ b/library/static/etc/init.d/russ
@@ -21,9 +21,11 @@ start() {
 	# start servers
 	filenames=`(cd /etc/russ/init; ls * | grep -v README)`
 	for filename in ${filenames}; do
-		echo -n "Starting server (${filename}) ... "
-		/etc/russ/init/${filename} start
-		[ $? -eq 0 ] && echo "OK" || echo "FAILED"
+		if ( /etc/russ/init/${filename} check ); then
+			echo -n "Starting server (${filename}) ... "
+			/etc/russ/init/${filename} start
+			[ $? -eq 0 ] && echo "OK" || echo "FAILED"
+		fi
 	done
 }
 
@@ -31,9 +33,11 @@ stop() {
 	# stop servers
 	filenames=`(cd /etc/russ/init; ls * | grep -v README)`
 	for filename in ${filenames}; do
-		echo -n "Stopping server (${filename}) ... "
-		/etc/russ/init/${filename} stop
-		[ $? -eq 0 ] && echo "OK" || echo "FAILED"
+		if ( /etc/russ/init/${filename} check ); then
+			echo -n "Stopping server (${filename}) ... "
+			/etc/russ/init/${filename} stop
+			[ $? -eq 0 ] && echo "OK" || echo "FAILED"
+		fi
 	done
 }
 
