(RUSSNG-871) Enhance rurun to support targetspec with decrement

diff --git a/tools/static/usr/bin/rurun b/tools/static/usr/bin/rurun
--- a/tools/static/usr/bin/rurun
+++ b/tools/static/usr/bin/rurun
@@ -24,7 +24,8 @@
 # target ids. target spec:
 # a - individual item
 # a:b - range a to b (non-inclusive), step 1
-# a:b:c - range a to b (non-inclusive), step c (where c is positive)
+# a:b:c - range a to b (includes a, not b), step c (where c is
+# positive or negative)
 function get_target_ids {
 	local target_ids=""
 	local head rest start end step
@@ -42,6 +43,9 @@ function get_target_ids {
 		endstep=${head#*:}
 		end=${endstep%%:*}
 		step=${endstep#*:}
+		if [ "${step}" = "${endstep}" ]; then
+			step=""
+		fi
 
 		# replace strings with integers
 		if [ "${start}" = "" ]; then
@@ -49,7 +53,7 @@ function get_target_ids {
 		fi
 		if [ "${end}" = "" ]; then
 			# implicit use of RURUN_PNET_ADDR
-			end=$(rurun --count)
+		        end=$(ruexec "${RURUN_PNET_ADDR}/count")
 			if [ $? -ne 0 ]; then
 				echo "error: bad end" 1>&2
 				exit 1
@@ -64,21 +68,30 @@ function get_target_ids {
 			# single item
 			target_ids="${target_ids} ${start}"
 		else
-			if [ "${step}" = "${endstep}" -a "${end}" = "${endstep}" ]; then
-				step=1
-			fi
 			# range (expect integers)
-			if [ ${start} -gt ${end} ]; then
-				echo "error: bad range (${start}:${end})" 1>&2
-				exit 1
-			elif [ ${step} -le 0 ]; then
-				echo "error: bad step (${step})" 1>&2
-				exit 1
+			if [ ${start} -le ${end} ]; then
+				if [ ${step} -le 0 ]; then
+					echo "error: bad step (${step})" 1>&2
+					exit 1
+				fi
+
+				# increment
+				while [ ${start} -lt ${end} ]; do
+					target_ids="${target_ids} ${start}"
+					((start=start+step))
+				done
+			else
+				if [ ${step} -ge 0 ]; then
+					echo "error: bad step (${step})" 1>&2
+					exit 1
+				fi
+
+				#decrement
+				while [ ${start} -gt ${end} ]; do
+					target_ids="${target_ids} ${start}"
+					((start=start+step))
+				done
 			fi
-			while [ ${start} -lt ${end} ]; do
-				target_ids="${target_ids} ${start}"
-				((start=start+step))
-			done
 		fi
 	done
 	echo ${target_ids}
@@ -98,8 +111,9 @@ If --count is specified, then the number of pnet targets is printed.
 targetspec is a comma separated list of one or more of:
 * value (e.g., 10)
 * start:end (e.g., 0:3 which is equivalent to 0,1,2)
-* start:end:step (e.g., 0:4:2 which is equivalent to 0,2)
-where start must be less than end, and step must be positive.
+* start:end:step (e.g., 0:4:2 which is equivalent to 0,2); if start
+  is greater than end, step must be negative (e.g., 3:0:-1 is
+  equivalent to 3,2,1)
 
 Options:
 -a|--attr <name>=<value>
@@ -201,8 +215,6 @@ while [ $# -gt 0 ]; do
 	esac
 done
 
-targets=$(get_target_ids "${targetspec}")
-
 # dynamically start pnet server if necessary
 if [ -z "${RURUN_PNET_ADDR}" ]; then
 	if [ -n "${RURUN_PNET_TARGETSFILE}" ]; then
@@ -215,6 +227,9 @@ if [ -z "${RURUN_PNET_ADDR}" ]; then
 	# ensure cleanup of pnet server
 	trap "kill -HUP -$$" EXIT
 fi
+
+# convert targetspec to list of targets
+targets=$(get_target_ids "${targetspec}")
 
 # debugging output
 if [ -n "${RURUN_DEBUG}" ]; then
