(RUSSNG-705) Exit with error for bad cmd

diff --git a/tools/static/usr/sbin/ruservice b/tools/static/usr/sbin/ruservice
--- a/tools/static/usr/sbin/ruservice
+++ b/tools/static/usr/sbin/ruservice
@@ -154,6 +154,10 @@ elif [ $# -eq 2 ]; then
 	restart)
 		restart
 		;;
+	*)
+		echo "error: bad/missing arguments"
+		exit 1
+		;;
 	esac
 else
 	echo "error: bad/missing arguments" 1>&2
